export type VideoProvider = "youtube" | "mp4";
export type VideoMode = "embed" | "external" | "mp4";
export type VideoPriority = "primary" | "reference";
export type VideoCategory =
  | "airway"
  | "resuscitation"
  | "cardiac"
  | "respiratory"
  | "neuro"
  | "sepsis"
  | "metabolic"
  | "trauma";

export type CompanionVideo = {
  slug: string;
  chapterSlug: string;
  title: string;
  description: string;
  provider: VideoProvider;
  mode: VideoMode;
  priority: VideoPriority;
  category: VideoCategory;
  watchUrl: string;
  youtubeId?: string;
  src?: string;
  durationLabel?: string;
  speaker?: string;
};

/*
 * These entries come from the local video sandbox, but the chapter mappings have
 * been reconciled against the chapter slugs that exist in this repository.
 */
export const companionVideos = [
  {
    slug: "airway-management",
    chapterSlug: "1-1-abcde-sample",
    title: "Airway management",
    description:
      "Manual airway manoeuvres, adjuncts, supraglottic and infraglottic devices, and the difference between oxygenation and ventilation",
    provider: "youtube",
    mode: "external",
    priority: "primary",
    category: "airway",
    watchUrl: "https://www.youtube.com/watch?v=qhMGlICGdtg",
    youtubeId: "qhMGlICGdtg",
    speaker: "Dr. Ivan Vuksan",
  },
  {
    slug: "deteriorating-patient-overview",
    chapterSlug: "1-1-abcde-sample",
    title: "Deteriorating patient",
    description: "An ABCDE overview covering key interventions and first-line management goals",
    provider: "youtube",
    mode: "external",
    priority: "primary",
    category: "airway",
    watchUrl: "https://www.youtube.com/watch?v=0Z5TYQTrOKI",
    youtubeId: "0Z5TYQTrOKI",
  },
  {
    slug: "als-guidelines",
    chapterSlug: "1-4-als-algorithm",
    title: "ALS guidelines",
    description: "A step-by-step walkthrough of the ALS algorithm and its decision points",
    provider: "youtube",
    mode: "external",
    priority: "primary",
    category: "resuscitation",
    watchUrl: "https://www.youtube.com/watch?v=jL8_zzu2JbI",
    youtubeId: "jL8_zzu2JbI",
  },
  {
    slug: "arrest-scenario",
    chapterSlug: "1-4-als-algorithm",
    title: "Arrest scenario",
    description: "A full cardiac arrest scenario from ABCDE assessment through resuscitation",
    provider: "youtube",
    mode: "external",
    priority: "primary",
    category: "resuscitation",
    watchUrl: "https://www.youtube.com/watch?v=Jno4QKpRy4c",
    youtubeId: "Jno4QKpRy4c",
  },
  {
    slug: "safe-defibrillation",
    chapterSlug: "1-4-als-algorithm",
    title: "Safe defibrillation",
    description: "Safe defibrillation technique and team setup",
    provider: "youtube",
    mode: "external",
    priority: "primary",
    category: "resuscitation",
    watchUrl: "https://www.youtube.com/watch?v=iFs4Jo6rpP8",
    youtubeId: "iFs4Jo6rpP8",
  },
  {
    slug: "acs-overview",
    chapterSlug: "2-1-acs",
    title: "Acute coronary syndrome",
    description: "Initial ACS assessment, ECG patterns, culprit-vessel clues, and additional leads",
    provider: "youtube",
    mode: "external",
    priority: "primary",
    category: "cardiac",
    watchUrl: "https://www.youtube.com/watch?v=ZmZOTNwrLyI",
    youtubeId: "ZmZOTNwrLyI",
  },
  {
    slug: "tachybrady-overview",
    chapterSlug: "2-2-arrhythmias",
    title: "Tachycardia and bradycardia",
    description: "How to approach tachycardia and bradycardia algorithms when adverse signs are present",
    provider: "youtube",
    mode: "external",
    priority: "primary",
    category: "cardiac",
    watchUrl: "https://www.youtube.com/watch?v=dpVdk-Nj554",
    youtubeId: "dpVdk-Nj554",
  },
  {
    slug: "zoll-defib",
    chapterSlug: "2-2-arrhythmias",
    title: "ZOLL defibrillator reference",
    description: "Monitor-defibrillator orientation for ZOLL devices",
    provider: "youtube",
    mode: "external",
    priority: "reference",
    category: "cardiac",
    watchUrl: "https://www.youtube.com/watch?v=5qfIRPxoHuw",
    youtubeId: "5qfIRPxoHuw",
  },
  {
    slug: "lifepak-pace",
    chapterSlug: "2-2-arrhythmias",
    title: "LIFEPAK 15 pacing",
    description: "Pacing workflow on the LIFEPAK 15",
    provider: "youtube",
    mode: "external",
    priority: "reference",
    category: "cardiac",
    watchUrl: "https://www.youtube.com/watch?v=BbX0ySF8CQE",
    youtubeId: "BbX0ySF8CQE",
  },
  {
    slug: "zoll-cardioversion",
    chapterSlug: "2-2-arrhythmias",
    title: "ZOLL cardioversion",
    description: "Synchronized cardioversion workflow on ZOLL devices",
    provider: "youtube",
    mode: "external",
    priority: "reference",
    category: "cardiac",
    watchUrl: "https://www.youtube.com/watch?v=C3Tx0eAkM-c",
    youtubeId: "C3Tx0eAkM-c",
  },
  {
    slug: "lifepak-cardioversion",
    chapterSlug: "2-2-arrhythmias",
    title: "LIFEPAK 15 defib and sync cardioversion",
    description: "Defibrillation and synchronized cardioversion on the LIFEPAK 15",
    provider: "youtube",
    mode: "external",
    priority: "reference",
    category: "cardiac",
    watchUrl: "https://www.youtube.com/watch?v=xEtyBXyFTDg",
    youtubeId: "xEtyBXyFTDg",
  },
  {
    slug: "abg-overview",
    chapterSlug: "3-3-abg",
    title: "ABG interpretation",
    description: "A short introduction to a simple ABG interpretation approach",
    provider: "youtube",
    mode: "external",
    priority: "primary",
    category: "respiratory",
    watchUrl: "https://www.youtube.com/watch?v=3FiubE4aNIo",
    youtubeId: "3FiubE4aNIo",
  },
  {
    slug: "anaphylaxis-overview",
    chapterSlug: "3-4-anaphylaxis",
    title: "Anaphylaxis",
    description: "Basic anaphylaxis pathophysiology and the first steps in assessment and treatment",
    provider: "youtube",
    mode: "external",
    priority: "primary",
    category: "respiratory",
    watchUrl: "https://www.youtube.com/watch?v=VSyI2-Llyfc",
    youtubeId: "VSyI2-Llyfc",
  },
  {
    slug: "asthma-attack",
    chapterSlug: "3-5-bronchospasm",
    title: "Asthma attack",
    description: "Initial assessment and management of an acute asthma attack",
    provider: "youtube",
    mode: "external",
    priority: "primary",
    category: "respiratory",
    watchUrl: "https://www.youtube.com/watch?v=ct-NFQOIb9U",
    youtubeId: "ct-NFQOIb9U",
  },
  {
    slug: "acute-bronchospasm",
    chapterSlug: "3-5-bronchospasm",
    title: "Acute bronchospasm",
    description: "Initial assessment and management of an acute COPD exacerbation",
    provider: "youtube",
    mode: "external",
    priority: "reference",
    category: "respiratory",
    watchUrl: "https://www.youtube.com/watch?v=805WeBl27Ms",
    youtubeId: "805WeBl27Ms",
  },
  {
    slug: "pulmonary-oedema-overview",
    chapterSlug: "3-6-pulm-oedema",
    title: "Cardiogenic pulmonary oedema",
    description: "Clinical presentation and treatment options in cardiogenic pulmonary oedema",
    provider: "youtube",
    mode: "external",
    priority: "primary",
    category: "respiratory",
    watchUrl: "https://www.youtube.com/watch?v=P3e-XBu7QhM",
    youtubeId: "P3e-XBu7QhM",
  },
  {
    slug: "gcs-overview",
    chapterSlug: "4-1-neuro",
    title: "Glasgow Coma Scale overview",
    description: "When to assess GCS and how to score each component",
    provider: "youtube",
    mode: "external",
    priority: "primary",
    category: "neuro",
    watchUrl: "https://www.youtube.com/watch?v=YpKImfz8OcQ",
    youtubeId: "YpKImfz8OcQ",
  },
  {
    slug: "gcs-demo",
    chapterSlug: "4-1-neuro",
    title: "Glasgow Coma Scale demo",
    description: "Three demonstration scenarios showing GCS assessment in practice",
    provider: "youtube",
    mode: "external",
    priority: "reference",
    category: "neuro",
    watchUrl: "https://www.youtube.com/watch?v=R4E1-iN2dH4",
    youtubeId: "R4E1-iN2dH4",
  },
  {
    slug: "brain-oedema-overview",
    chapterSlug: "4-1-neuro",
    title: "Brain oedema overview",
    description: "Basic pathophysiology, differential diagnosis, and initial assessment of brain oedema",
    provider: "youtube",
    mode: "external",
    priority: "primary",
    category: "neuro",
    watchUrl: "https://www.youtube.com/watch?v=DyZRwkgPpTU",
    youtubeId: "DyZRwkgPpTU",
  },
  {
    slug: "brain-oedema-treatment",
    chapterSlug: "4-1-neuro",
    title: "Brain oedema treatment",
    description: "Core treatment strategies for patients with brain oedema",
    provider: "youtube",
    mode: "external",
    priority: "reference",
    category: "neuro",
    watchUrl: "https://www.youtube.com/watch?v=i11NAZ_SG2o",
    youtubeId: "i11NAZ_SG2o",
  },
  {
    slug: "sepsis-qsofa-overview",
    chapterSlug: "5-1-sepsis",
    title: "Sepsis, SOFA and qSOFA",
    description: "Early recognition of sepsis and septic shock, with SOFA and qSOFA in context",
    provider: "youtube",
    mode: "external",
    priority: "primary",
    category: "sepsis",
    watchUrl: "https://www.youtube.com/watch?v=2tALfO5tjGE",
    youtubeId: "2tALfO5tjGE",
  },
  {
    slug: "sepsis-first-hour-bundle",
    chapterSlug: "5-1-sepsis",
    title: "Sepsis first hour bundle",
    description: "The first-hour treatment bundle for suspected sepsis or septic shock",
    provider: "youtube",
    mode: "external",
    priority: "reference",
    category: "sepsis",
    watchUrl: "https://www.youtube.com/watch?v=p3pWJ-ody24",
    youtubeId: "p3pWJ-ody24",
  },
  {
    slug: "acute-poisoning",
    chapterSlug: "4-3-poisoning",
    title: "Acute poisoning",
    description: "Initial assessment, definitions, and specific treatment options such as antidotes",
    provider: "youtube",
    mode: "external",
    priority: "primary",
    category: "metabolic",
    watchUrl: "https://www.youtube.com/watch?v=ZhK02Mwgons",
    youtubeId: "ZhK02Mwgons",
  },
  {
    slug: "iv-fluids",
    chapterSlug: "6-1-iv-fluids",
    title: "Intravenous fluids",
    description: "The physiology of IV fluids, common fluid types, and practical indications",
    provider: "youtube",
    mode: "external",
    priority: "primary",
    category: "metabolic",
    watchUrl: "https://youtu.be/Plx9_q_3KN0",
    youtubeId: "Plx9_q_3KN0",
  },
  {
    slug: "potassium-disorders",
    chapterSlug: "6-2-electrolytes",
    title: "Hypo- and hyperkalaemia",
    description: "Assessment and treatment of hypo- and hyperkalaemia",
    provider: "youtube",
    mode: "external",
    priority: "primary",
    category: "metabolic",
    watchUrl: "https://www.youtube.com/watch?v=7qlggkVRFQo",
    youtubeId: "7qlggkVRFQo",
  },
  {
    slug: "haemorrhagic-shock",
    chapterSlug: "6-3-haemorrhage",
    title: "Haemorrhagic shock and haemorrhage",
    description: "Classification, blood-loss assessment, and early management of major haemorrhage",
    provider: "youtube",
    mode: "external",
    priority: "primary",
    category: "trauma",
    watchUrl: "https://www.youtube.com/watch?v=YxWGLMMGTf4",
    youtubeId: "YxWGLMMGTf4",
  },
  {
    slug: "trauma-overview",
    chapterSlug: "7-1-trauma",
    title: "Trauma overview",
    description: "An overview of trauma assessment with ITLS and ETC frameworks",
    provider: "youtube",
    mode: "external",
    priority: "primary",
    category: "trauma",
    watchUrl: "https://www.youtube.com/watch?v=dYJfiodiNmw",
    youtubeId: "dYJfiodiNmw",
  },
  {
    slug: "thoracic-trauma",
    chapterSlug: "7-1-trauma",
    title: "Thoracic trauma",
    description: "Life-threatening thoracic injuries, key signs, and immediate management",
    provider: "youtube",
    mode: "external",
    priority: "reference",
    category: "trauma",
    watchUrl: "https://www.youtube.com/watch?v=vzlHiXSaYaY",
    youtubeId: "vzlHiXSaYaY",
  },
  {
    slug: "abdominal-trauma",
    chapterSlug: "7-1-trauma",
    title: "Abdominal trauma",
    description: "Initial assessment of suspected abdominal injury, anatomy, and immediate interventions",
    provider: "youtube",
    mode: "external",
    priority: "reference",
    category: "trauma",
    watchUrl: "https://www.youtube.com/watch?v=rqSEen2AJ3M",
    youtubeId: "rqSEen2AJ3M",
  },
  {
    slug: "trauma-primary-survey",
    chapterSlug: "7-1-trauma",
    title: "Trauma primary survey",
    description: "A demonstration of the trauma primary survey",
    provider: "youtube",
    mode: "external",
    priority: "reference",
    category: "trauma",
    watchUrl: "https://www.youtube.com/watch?v=4Zzn0EDPPnM",
    youtubeId: "4Zzn0EDPPnM",
  },
  {
    slug: "pelvic-splint",
    chapterSlug: "7-1-trauma",
    title: "Pelvic splint",
    description: "How to apply a pelvic splint",
    provider: "youtube",
    mode: "external",
    priority: "reference",
    category: "trauma",
    watchUrl: "https://www.youtube.com/watch?v=RdZGddl-bfg",
    youtubeId: "RdZGddl-bfg",
  },
  {
    slug: "helmet-removal",
    chapterSlug: "7-1-trauma",
    title: "Helmet removal",
    description: "Helmet removal with continuous patient assessment and communication",
    provider: "youtube",
    mode: "external",
    priority: "reference",
    category: "trauma",
    watchUrl: "https://www.youtube.com/watch?v=3AKn3PAm2bc",
    youtubeId: "3AKn3PAm2bc",
  },
  {
    slug: "c-spine-immobilisation",
    chapterSlug: "7-1-trauma",
    title: "C-spine immobilisation",
    description: "How to immobilize the cervical spine",
    provider: "youtube",
    mode: "external",
    priority: "reference",
    category: "trauma",
    watchUrl: "https://www.youtube.com/watch?v=OwS84fMje8Y",
    youtubeId: "OwS84fMje8Y",
  },
  {
    slug: "burns-overview",
    chapterSlug: "7-2-burns",
    title: "Burns",
    description: "Burn classification, high-risk features, and initial management",
    provider: "youtube",
    mode: "external",
    priority: "reference",
    category: "trauma",
    watchUrl: "https://www.youtube.com/watch?v=VCx9d0eXZVg",
    youtubeId: "VCx9d0eXZVg",
  },
] as const satisfies readonly CompanionVideo[];

export function getVideosForChapter(chapterSlug: string, priority?: VideoPriority) {
  return companionVideos.filter((video) => {
    if (video.chapterSlug !== chapterSlug) {
      return false;
    }

    return priority ? video.priority === priority : true;
  });
}
