export type VideoProvider = "youtube" | "mp4";
export type VideoMode = "embed" | "external" | "mp4";
export type VideoPriority = "primary" | "reference";
export type VideoCategory =
  | "airway"
  | "resuscitation"
  | "cardiac"
  | "respiratory"
  | "neuro"
  | "sepsis"
  | "metabolic"
  | "trauma";

export type CompanionVideo = {
  slug: string;
  chapterSlug: string;
  title: string;
  description: string;
  provider: VideoProvider;
  mode: VideoMode;
  priority: VideoPriority;
  category: VideoCategory;
  watchUrl: string;
  youtubeId?: string;
  src?: string;
  durationLabel?: string;
  speaker?: string;
};

/*
 * These entries come from the local video sandbox, but the chapter mappings have
 * been reconciled against the chapter slugs that exist in this repository.
 */
export const companionVideos = [
  {
    slug: "airway-management",
    chapterSlug: "1-1-abcde-sample",
    title: "Airway management",
    description:
      "Dr. Ivan Vuksan covers manual airway manoeuvres, adjuncts, supraglottic and infraglottic devices, and the practical distinction between oxygenation and ventilation",
    provider: "youtube",
    mode: "external",
    priority: "primary",
    category: "airway",
    watchUrl: "https://www.youtube.com/watch?v=qhMGlICGdtg",
    youtubeId: "qhMGlICGdtg",
    speaker: "Dr. Ivan Vuksan",
  },
  {
    slug: "deteriorating-patient-overview",
    chapterSlug: "1-1-abcde-sample",
    title: "Deteriorating patient",
    description: "In this video-tutorial dr. Katarina Božić thoroughly presents each of the components of ABCDE algorithm, possible interventions and goals of initial management.",
    provider: "youtube",
    mode: "external",
    priority: "primary",
    category: "airway",
    watchUrl: "https://www.youtube.com/watch?v=0Z5TYQTrOKI",
    youtubeId: "0Z5TYQTrOKI",
  },
  {
    slug: "als-guidelines",
    chapterSlug: "1-4-als-algorithm",
    title: "ALS guidelines",
    description: "In this obligatory video-tutorial dr. Matej Bura presents the algorithm for cardiopulmonary resuscitation and analyses every part of the algorithm in details",
    provider: "youtube",
    mode: "external",
    priority: "primary",
    category: "resuscitation",
    watchUrl: "https://www.youtube.com/watch?v=jL8_zzu2JbI",
    youtubeId: "jL8_zzu2JbI",
  },
  {
    slug: "arrest-scenario",
    chapterSlug: "1-4-als-algorithm",
    title: "Arrest scenario",
    description: "In this video-demonstration of cardiac arrest dr. Jan Maroević, dr. Matej Bura, dr. Katarina Božić and dr. Ivan Vuksan demonstrate the initial management of a patient through the ABCDE and SAMPLE approach, followed by cardiopulmonary resuscitation in accordance with ERC Advanced Life Support guidelines, once the patient goes to cardiac arrest.",
    provider: "youtube",
    mode: "external",
    priority: "primary",
    category: "resuscitation",
    watchUrl: "https://www.youtube.com/watch?v=Jno4QKpRy4c",
    youtubeId: "Jno4QKpRy4c",
  },
  {
    slug: "safe-defibrillation",
    chapterSlug: "1-4-als-algorithm",
    title: "Safe defibrillation",
    description: "In this video-tutorial dr. Jan Maroević, dr. Matej Bura and doc. Janja Tarčuković demonstrate safe defibrillation.",
    provider: "youtube",
    mode: "external",
    priority: "primary",
    category: "resuscitation",
    watchUrl: "https://www.youtube.com/watch?v=iFs4Jo6rpP8",
    youtubeId: "iFs4Jo6rpP8",
  },
  {
    slug: "acs-overview",
    chapterSlug: "2-1-acs",
    title: "Acute coronary syndrome",
    description: "In this obligatory video-tutorial, dr. Ivan Ševeljević talks about initial assessment and management of a patient with acute coronary syndrome, explains the basic morphological findings on ECG, together with different patterns that can be observed depending the involved coronary artery, as well as indications for recording additional ECG-leads",
    provider: "youtube",
    mode: "external",
    priority: "primary",
    category: "cardiac",
    watchUrl: "https://www.youtube.com/watch?v=ZmZOTNwrLyI",
    youtubeId: "ZmZOTNwrLyI",
  },
  {
    slug: "tachybrady-overview",
    chapterSlug: "2-2-arrhythmias",
    title: "Tachycardia and bradycardia",
    description: "In this obligatory video-tutorial dr. Matej Bura explains the tachy- and bradycardia algorithm. Mind the difference in approach to both tachy- and bradycardia whether there are adverse signs present (e.g. shock, signs of heart failure, signs and symptoms of myocardial ischaemia, syncope), as well as how do we recognize them in our everyday practice.",
    provider: "youtube",
    mode: "external",
    priority: "primary",
    category: "cardiac",
    watchUrl: "https://www.youtube.com/watch?v=dpVdk-Nj554",
    youtubeId: "dpVdk-Nj554",
  },
  {
    slug: "zoll-defib",
    chapterSlug: "2-2-arrhythmias",
    title: "ZOLL defibrillator reference",
    description: "Reference equipment video for monitor/defibrillator orientation.",
    provider: "youtube",
    mode: "external",
    priority: "reference",
    category: "cardiac",
    watchUrl: "https://www.youtube.com/watch?v=5qfIRPxoHuw",
    youtubeId: "5qfIRPxoHuw",
  },
  {
    slug: "lifepak-pace",
    chapterSlug: "2-2-arrhythmias",
    title: "LIFEPAK 15 pacing",
    description: "Reference equipment video for pacing workflow.",
    provider: "youtube",
    mode: "external",
    priority: "reference",
    category: "cardiac",
    watchUrl: "https://www.youtube.com/watch?v=BbX0ySF8CQE",
    youtubeId: "BbX0ySF8CQE",
  },
  {
    slug: "zoll-cardioversion",
    chapterSlug: "2-2-arrhythmias",
    title: "ZOLL cardioversion",
    description: "Reference equipment video for synchronised cardioversion.",
    provider: "youtube",
    mode: "external",
    priority: "reference",
    category: "cardiac",
    watchUrl: "https://www.youtube.com/watch?v=C3Tx0eAkM-c",
    youtubeId: "C3Tx0eAkM-c",
  },
  {
    slug: "lifepak-cardioversion",
    chapterSlug: "2-2-arrhythmias",
    title: "LIFEPAK 15 defib and sync cardioversion",
    description: "Reference equipment video for defibrillation and synchronised cardioversion.",
    provider: "youtube",
    mode: "external",
    priority: "reference",
    category: "cardiac",
    watchUrl: "https://www.youtube.com/watch?v=xEtyBXyFTDg",
    youtubeId: "xEtyBXyFTDg",
  },
  {
    slug: "abg-overview",
    chapterSlug: "3-3-abg",
    title: "ABG interpretation",
    description: "An educational video made by dr. Erika Šuper-Petrinjac, providing a short introduction and explanation for a simple ABGs analysis approach.",
    provider: "youtube",
    mode: "external",
    priority: "primary",
    category: "respiratory",
    watchUrl: "https://www.youtube.com/watch?v=3FiubE4aNIo",
    youtubeId: "3FiubE4aNIo",
  },
  {
    slug: "anaphylaxis-overview",
    chapterSlug: "3-4-anaphylaxis",
    title: "Anaphylaxis",
    description: "In this short video-tutorial, dr. Ivana Jurinčić explains the basic pathophysiology of anaphylaxis and the steps that need to be performed during initial assessment and management of a patients with this medical emergency.",
    provider: "youtube",
    mode: "external",
    priority: "primary",
    category: "respiratory",
    watchUrl: "https://www.youtube.com/watch?v=VSyI2-Llyfc",
    youtubeId: "VSyI2-Llyfc",
  },
  {
    slug: "asthma-attack",
    chapterSlug: "3-5-bronchospasm",
    title: "Asthma attack",
    description: "In this video tutorial dr. Ana Pičuljan explains the initial assessment and management of a patient with asthma attack.",
    provider: "youtube",
    mode: "external",
    priority: "primary",
    category: "respiratory",
    watchUrl: "https://www.youtube.com/watch?v=ct-NFQOIb9U",
    youtubeId: "ct-NFQOIb9U",
  },
  {
    slug: "acute-bronchospasm",
    chapterSlug: "3-5-bronchospasm",
    title: "Acute bronchospasm",
    description: "In this video tutorial dr. Ana Pičuljan explains the initial assessment and management of a patient with acute exacerbation of COPD.",
    provider: "youtube",
    mode: "external",
    priority: "reference",
    category: "respiratory",
    watchUrl: "https://www.youtube.com/watch?v=805WeBl27Ms",
    youtubeId: "805WeBl27Ms",
  },
  {
    slug: "pulmonary-oedema-overview",
    chapterSlug: "3-6-pulm-oedema",
    title: "Cardiogenic pulmonary edema",
    description: "In this video lecture, dr. Erika Šuper-Petrinjac goes through specifics of clinical presentation of a patient with cardiogenic pulmonary oedema, as well as the therapeutic options.",
    provider: "youtube",
    mode: "external",
    priority: "primary",
    category: "respiratory",
    watchUrl: "https://www.youtube.com/watch?v=P3e-XBu7QhM",
    youtubeId: "P3e-XBu7QhM",
  },
  {
    slug: "gcs-overview",
    chapterSlug: "4-1-neuro",
    title: "Glasgow Coma Scale overview",
    description: "In this obligatory video-tutorial dr. Jan Maroevic explains the indications for performing GCS assessment, as well as three different segments we are assessing when calculated GCS score.",
    provider: "youtube",
    mode: "external",
    priority: "primary",
    category: "neuro",
    watchUrl: "https://www.youtube.com/watch?v=YpKImfz8OcQ",
    youtubeId: "YpKImfz8OcQ",
  },
  {
    slug: "gcs-demo",
    chapterSlug: "4-1-neuro",
    title: "Glasgow Coma Scale demo",
    description: "In this obligatory video-demonstration dr. Jan Maroevic and dr. Matej Buta demonstrate three different clinical scenarios with GCS assessment, starting from a patient with suspected concussion and GCS of 13, then spontaneously collape during physical activity resulting in a patient GCS of 8, and finally patient with signs of decerebration and GCS of 4..",
    provider: "youtube",
    mode: "external",
    priority: "reference",
    category: "neuro",
    watchUrl: "https://www.youtube.com/watch?v=R4E1-iN2dH4",
    youtubeId: "R4E1-iN2dH4",
  },
  {
    slug: "brain-oedema-overview",
    chapterSlug: "4-1-neuro",
    title: "Brain edema overview",
    description: "In this obligatory video-tutorial dr. Jan Maroevic goes through basic pathophysiology and differential diagnosis of brain oedema, as well the initial assessment of a patient with this medical emergency.",
    provider: "youtube",
    mode: "external",
    priority: "primary",
    category: "neuro",
    watchUrl: "https://www.youtube.com/watch?v=DyZRwkgPpTU",
    youtubeId: "DyZRwkgPpTU",
  },
  {
    slug: "brain-oedema-treatment",
    chapterSlug: "4-1-neuro",
    title: "Brain edema treatment",
    description: "In the second part of this obligatory video-tutorial, dr. Jan Maroevic explains the basic therapeutic strategies in patients suffering from brain oedema.",
    provider: "youtube",
    mode: "external",
    priority: "reference",
    category: "neuro",
    watchUrl: "https://www.youtube.com/watch?v=i11NAZ_SG2o",
    youtubeId: "i11NAZ_SG2o",
  },
  {
    slug: "sepsis-qsofa-overview",
    chapterSlug: "5-1-sepsis",
    title: "Sepsis, SOFA and qSOFA",
    description: "In this obligatory video-tutorial doc. Janja Tarcukovic explains the importance of early recognition of sepsis and septic shock, and provides an insight into the available tools that help us in this process.",
    provider: "youtube",
    mode: "external",
    priority: "primary",
    category: "sepsis",
    watchUrl: "https://www.youtube.com/watch?v=2tALfO5tjGE",
    youtubeId: "2tALfO5tjGE",
  },
  {
    slug: "sepsis-first-hour-bundle",
    chapterSlug: "5-1-sepsis",
    title: "Sepsis first hour bundle",
    description: "In this video-tutorial, doc. Janja Tarcukovic explains the treatment that should be applied in patients with suspected sepsis/septic shock, starting within the first hour after suspicion has been risen",
    provider: "youtube",
    mode: "external",
    priority: "reference",
    category: "sepsis",
    watchUrl: "https://www.youtube.com/watch?v=p3pWJ-ody24",
    youtubeId: "p3pWJ-ody24",
  },
  {
    slug: "acute-poisoning",
    chapterSlug: "4-3-poisoning",
    title: "Acute poisoning",
    description: "In this video-tutorial dr. Anja Wolfand defines acute poisoning, how an initial approach to a patient should look like, and what are possible specific treatment measures (e.g. antidotes)",
    provider: "youtube",
    mode: "external",
    priority: "primary",
    category: "metabolic",
    watchUrl: "https://www.youtube.com/watch?v=ZhK02Mwgons",
    youtubeId: "ZhK02Mwgons",
  },
  {
    slug: "iv-fluids",
    chapterSlug: "6-1-iv-fluids",
    title: "Intravenous fluids",
    description: "In this video-tutorial doc. Janja Tarcukovic explains the physiological basis behind the application of intravenous fluids, a medication with their indications, doses and complication. After the introduction, basic types of intravenous fluids are mentioned, together with the most common indications for using them.",
    provider: "youtube",
    mode: "external",
    priority: "primary",
    category: "metabolic",
    watchUrl: "https://youtu.be/Plx9_q_3KN0",
    youtubeId: "Plx9_q_3KN0",
  },
  {
    slug: "potassium-disorders",
    chapterSlug: "6-2-electrolytes",
    title: "Hypo- and hyperkalaemia",
    description: "In this obligatory video-tutorial, dr. Berislav Barbalic explains the basic pathophysiology behind derrangements in potassium levels, how do we assess the patient in order to diagnose these derrangements, and what therapeutic strategies to apply in patients with hypo- or hyperkalaemia.",
    provider: "youtube",
    mode: "external",
    priority: "primary",
    category: "metabolic",
    watchUrl: "https://www.youtube.com/watch?v=7qlggkVRFQo",
    youtubeId: "7qlggkVRFQo",
  },
  {
    slug: "haemorrhagic-shock",
    chapterSlug: "6-3-haemorrhage",
    title: "Hemorrhagic shock and hemorrhage",
    description: "In this obligatory video-tutorial dr. Danijel Knezevic explains the basic pathophysiology of haemorrhage and haemorrhagic shock, how do we classify the bleeding and assess the blood loss and what are the couses of major bleeding, after which he describes what the initial assessment and management of a patient who is bleeding should look like.",
    provider: "youtube",
    mode: "external",
    priority: "primary",
    category: "trauma",
    watchUrl: "https://www.youtube.com/watch?v=YxWGLMMGTf4",
    youtubeId: "YxWGLMMGTf4",
  },
  {
    slug: "trauma-overview",
    chapterSlug: "7-1-trauma",
    title: "Trauma overview",
    description: "In this video-tutorial dr. Petra Šverko Zinaić explains the approach to trauma patients, what is politrauma, and gives an overview of two protocols for initial assessment and management of trauma patients in out-of-hospital and hospital setting (ITLS and ETC, respectively).",
    provider: "youtube",
    mode: "external",
    priority: "primary",
    category: "trauma",
    watchUrl: "https://www.youtube.com/watch?v=dYJfiodiNmw",
    youtubeId: "dYJfiodiNmw",
  },
  {
    slug: "thoracic-trauma",
    chapterSlug: "7-1-trauma",
    title: "Thoracic trauma",
    description: "In this obligatory video-tutorial dr. Nataša Mavrinac explains the basics of thoracic trauma, life-threatening injuries and potential life-threatening injuries, as well as their signs, sympthoms and immediate management",
    provider: "youtube",
    mode: "external",
    priority: "reference",
    category: "trauma",
    watchUrl: "https://www.youtube.com/watch?v=vzlHiXSaYaY",
    youtubeId: "vzlHiXSaYaY",
  },
  {
    slug: "abdominal-trauma",
    chapterSlug: "7-1-trauma",
    title: "Abdominal trauma",
    description: "In this video-tutorial dr. Marinka Otočan explains the primary approach to patient with suspected abdominal injury, how abdominal examination is made, the anatomy of abdominal region, the importance of history and mechanism of injury on initial assessment and important immediate interventions",
    provider: "youtube",
    mode: "external",
    priority: "reference",
    category: "trauma",
    watchUrl: "https://www.youtube.com/watch?v=rqSEen2AJ3M",
    youtubeId: "rqSEen2AJ3M",
  },
  {
    slug: "trauma-primary-survey",
    chapterSlug: "7-1-trauma",
    title: "Trauma primary survey",
    description: "In this video-demonstration dr. Mate Matešić, dr. Petra Šverko Zinaić, dr. Marinka Otočan and dr. Nataša Mavrinac show how to perform a primary survey on a trauma patient",
    provider: "youtube",
    mode: "external",
    priority: "reference",
    category: "trauma",
    watchUrl: "https://www.youtube.com/watch?v=4Zzn0EDPPnM",
    youtubeId: "4Zzn0EDPPnM",
  },
  {
    slug: "pelvic-splint",
    chapterSlug: "7-1-trauma",
    title: "Pelvic splint",
    description: "In this video-demonstration dr. Petra Šverko Zinaić, dr. Marinka Otočan and dr. Nataša Mavrinac show how to apply pelvic splint.",
    provider: "youtube",
    mode: "external",
    priority: "reference",
    category: "trauma",
    watchUrl: "https://www.youtube.com/watch?v=RdZGddl-bfg",
    youtubeId: "RdZGddl-bfg",
  },
  {
    slug: "helmet-removal",
    chapterSlug: "7-1-trauma",
    title: "Helmet removal",
    description: "In this video-demonstration dr. Marinka Otočan, dr. Nataša Mavrinac and dr. Petra Šverko Zinaić show how to remove a helmet. Mind the continuous assessment and communication with the patient. ",
    provider: "youtube",
    mode: "external",
    priority: "reference",
    category: "trauma",
    watchUrl: "https://www.youtube.com/watch?v=3AKn3PAm2bc",
    youtubeId: "3AKn3PAm2bc",
  },
  {
    slug: "c-spine-immobilisation",
    chapterSlug: "7-1-trauma",
    title: "C-spine immobilisation",
    description: "In this video-demonstration dr. Mate Matešić, dr. Petra Šverko Zinaić and dr. Nataša Mavrinac show how to immobilize cervical spine.",
    provider: "youtube",
    mode: "external",
    priority: "reference",
    category: "trauma",
    watchUrl: "https://www.youtube.com/watch?v=OwS84fMje8Y",
    youtubeId: "OwS84fMje8Y",
  },
  {
    slug: "burns-overview",
    chapterSlug: "7-2-burns",
    title: "Burns",
    description: "In this video-tutorial dr. Marko Milošević explains the basic definition of burn injury, the characteristics of electrical injury, how do we classify burns and what makes a patient high-risk for developing complication. On top of that, he presents the initial assessment and management of a burned patient",
    provider: "youtube",
    mode: "external",
    priority: "reference",
    category: "trauma",
    watchUrl: "https://www.youtube.com/watch?v=VCx9d0eXZVg",
    youtubeId: "VCx9d0eXZVg",
  },
] as const satisfies readonly CompanionVideo[];

export function getVideosForChapter(chapterSlug: string, priority?: VideoPriority) {
  return companionVideos.filter((video) => {
    if (video.chapterSlug !== chapterSlug) {
      return false;
    }

    return priority ? video.priority === priority : true;
  });
}
